server:
  port: 10004

spring:
  application:
    name: cars-service
  profiles:
    active:
    - prod


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs